image: dchevell/docker-release-maker:latest
clone:
  depth: full

pipelines:
  custom:
    create-release-base-6-adoptopenjdk8:
      - step:
          script:
            - git fetch --all
            - export BASE_BRANCH=base-6-adoptopenjdk8
            - export BASE_VERSION=6
            - export DOCKER_REPO=atlassian/confluence-server
            - export DOCKERFILE_VERSION_STRING=CONFLUENCE_VERSION
            - export GIT_USER=pipelinesagent
            - export GIT_EMAIL=pipelines-agent@atlassian.com
            - export MAC_PRODUCT_KEY=confluence
            - export TAG_SUFFIX=ubuntu-18.04-adoptopenjdk8
            - export SHOULD_CREATE_LATEST_TAG=true
            - python /usr/src/app/create_release.py
            - curl -X POST -H "Content-Type:application/json" -d '{"tag":"registry.hub.docker.com/atlassian/confluence-server:latest", "annotations":{"owner":"smadi"}}' \
              https://docker-scanner-web-service.us-east-1.prod.atl-paas.net/api/scan
  branches:
    base-6-adoptopenjdk8:
      - step:
          script:
            - git fetch --all
            - export BASE_BRANCH=base-6-adoptopenjdk8
            - export BASE_VERSION=6
            - export DOCKER_REPO=atlassian/confluence-server
            - export DOCKERFILE_VERSION_STRING=CONFLUENCE_VERSION
            - export GIT_USER=pipelinesagent
            - export GIT_EMAIL=pipelines-agent@atlassian.com
            - export MAC_PRODUCT_KEY=confluence
            - export TAG_SUFFIX=ubuntu-18.04-adoptopenjdk8
            - export SHOULD_CREATE_LATEST_TAG=true
            - python /usr/src/app/update_release.py
            - curl -X POST -H "Content-Type:application/json" -d '{"tag":"registry.hub.docker.com/atlassian/confluence-server:latest", "annotations":{"owner":"smadi"}}' \
              https://docker-scanner-web-service.us-east-1.prod.atl-paas.net/api/scan