#!/bin/bash
# See Github Actions secrets
CONFLUENCE_TEST_LICENSE=`echo ${CONFLUENCE_TEST_LICENSE} | tr -d '\n \t'`

sed "s~INJECT_LICENSE_HERE~${CONFLUENCE_TEST_LICENSE}~" confluence-home/confluence.cfg.xml.tmpl > confluence-home/confluence.cfg.xml
